### ISSUE TITLE
Bug: 当proxyConfig.ajax.query响应较快时（小于100毫秒），表格高度计算错误

### ISSUE THREAD

**Issue by TengChongChong** [vbenjs/vue-vben-admin#5035] opened 2024-12-05 05:57 UTC
### Version

Vben Admin V5

## 复现方式
注释 `/vue-vben-admin/apps/backend-mock/api/table/list.ts`中的`await sleep(600);`
![image](https://github.com/user-attachments/assets/95bee599-83b7-4e20-abb6-d7403feb6242)
![image](https://github.com/user-attachments/assets/ba0f8379-1939-4153-abef-dc7d884f575a)

刚开始怀疑是vxe-table的bug，但是使用未封装的vxe-table未复现此问题

### Reproduction

无

### System Info

```shell
Mac Chrome
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment] 2024-12-05 13:00
Duplicate of #5015

**Closed** 2024-12-11 05:46 UTC
Labels: duplicate, bug: pending triage

**Comment by TengChongChong** [comment] 2024-12-11 06:33
> Duplicate of #5015

此问题依然存在，更改窗口尺寸后刷新页面
![image](https://github.com/user-attachments/assets/098cef4f-567d-4403-8fd4-b32f40af1467)
