### ISSUE TITLE
Bug: 类似 官网示例-Vxe 表格-固定表头/列 这种字段多的表格横向滚动异常

### ISSUE THREAD

**Issue by youtao531** [vbenjs/vue-vben-admin#5036] opened 2024-12-05 06:01 UTC
### Version

Vben Admin V5

### Describe the bug?

类似 官网示例-Vxe 表格-固定表头/列 这种字段多的表格横向滚动异常，会导致搜索框和表格行的操作栏固定失效

![image](https://github.com/user-attachments/assets/5c9b990c-cc42-4ff3-b096-8a2413f70a45)

![1733378436404](https://github.com/user-attachments/assets/8a767e86-5640-4cff-9c79-e51902087f9c)

### Reproduction

官网示例-Vxe 表格-固定表头/列

### System Info

```shell
官网示例
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment] 2024-12-05 06:12
fixed in #5033

**Comment by mynetfan** [comment] 2024-12-05 08:18
Duplicate of #5028

**Closed by mynetfan** 2024-12-05 08:18 UTC
Labels: bug: pending triage
